### ISSUE TITLE
O link de confirmação de cadastro do e-mail apresenta erro.

### ISSUE THREAD

**Issue by iagovrocha** [unitedcodelab/plataforma-cursos#17]
**O link de confirmação de cadastro do e-mail apresenta erro.**

O link apresenta uma mensagem de erro na pagina.

**Descrição:**

Acessando o e-mail de confirmação de cadastro, e clicando no link de confirmação, a pagina apresenta um erro.

**Passos para Reproduzir:**

          1.  Efetuar o cadastro no site
          2.  Ir no e-mail (**O e-mail de confirmação de cadastro caiu no spam**)
          3.  Clicar no link de confirmação de cadastros
          
**Comportamento Esperado:**

Que ao clicar no link, aparecer na pagina o feedback de que a confirmação do cadastro foi efetuado. E um botão, para voltar ao site.

**Comportamento Observado:**

Mostra somente a mensagem de erro.

**Ambiente:**

- Sistema: Windows 10 Pro 22H2
- Navegador: Google Chrome Versão 126.0.6478.127 
- Versão do Software: 1.0.0-alpha

**Capturas de Tela:**

![image](https://github.com/user-attachments/assets/40800f79-53fc-4732-b3a4-1505ae9c543e)

**OBERSERÇÃO:** 

Mesmo com essa mensagem de erro. O login é efetuado normalmente

**Comment by antonionetu** [comment]
Eae Iago, blzzz?
Muito obrigado por reportar o problema! Logo logo vamos estar corrigindo ele 😉

**Comment by antonionetu** [comment]
https://github.com/unitedcodelab/plataforma-cursos/pull/22
