### ISSUE TITLE
A opção esqueceu senha não esta funcionando!

### ISSUE THREAD

**Issue by MateussCg** [unitedcodelab/plataforma-cursos#18]
Quando eu clico para trocar a senha, no caso o esqueceu senha, acaba que não é redirecionado para nenhum local.

![Captura de tela 2024-07-13 105306](https://github.com/user-attachments/assets/69d34ef2-6420-48b3-8df5-c82c7842fbeb)

Na URL, quando clica em esqueceu senha, vai aparecer uma hashtag.

Estou usando o:

> Windows 11 Pro

> 23H2

> Chrome

**Comment by antonionetu** [comment]
Opa! Eae Mateus blz??
De fato, isso nao esta funcionando ainda por causa que esquecemos de implementar essa feature 😅
Obrigado por avisar! Iremos implementar-la em breve

**Comment by antonionetu** [comment]
https://github.com/unitedcodelab/plataforma-cursos/pull/25

**Comment by antonionetu** [comment]
Ainda nao fecharei essa issue pois a feature de "Esqueci senha" ainda será implementada

**Comment by antonionetu** [comment]
https://github.com/unitedcodelab/plataforma-cursos/pull/27
