### ISSUE TITLE
Erro de confirmação de e-mail

### ISSUE THREAD

**Issue by DiegoPassosDev** [unitedcodelab/plataforma-cursos#21]
### Título: Validação de eimal
Ao clicar na validação enviada para minha caixa de e-mail um erro aparece na página.
 
### Descrição:
Realizei todo o procedimento de cadastro onde insiro minha matrícula UNIT, logo após adiciono e-mail institucional e crio um senha, coloco meu slug do GitHub e finalizo, logo após é enviado um e-mail de confirmação de cadastro e ao clicar no mesmo aparece o erro no navegador. 
 
 
### Comportamento Esperado:
Aparecer a tela de confirmação de cadastro e ir para tela de login.
 

 
### Ambiente:
- Sistema Operacional: Windows 11
- Navegador: Chrome 126.0.6478.127
- Versão do Software: 64 bits
 
### Capturas de Tela:
![image](https://github.com/user-attachments/assets/9fa8e3e2-2b0a-4d43-a3bb-0a9fec5c0c53)
 
### Logs ou Mensagens de Erro:
null value in column "biograph" of relation "entities_student" violates not-null constraint

**Comment by antonionetu** [comment]
https://github.com/unitedcodelab/plataforma-cursos/pull/24
